models
Transport-company/core pull request #1
Opened 2021-01-19 08:12 UTC by Gelnas

2021-01-19 08:36 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Returns.java
> +    @JoinColumn(name = "delivery_Id", referencedColumnName = "id")
delivery_Id -> delivery_id (строчная i)

2021-01-19 09:04 UTC, vibriss commented on src/main/java/com/training/core/model/Address.java
> +    @Column(name = "flat")
Правильнее именовать apartment

2021-01-19 09:06 UTC, vibriss commented on src/main/java/com/training/core/model/Tracking.java
> +    @Column(name = "registration_time")
Может, все-таки не дублировать с полем "creation_time"?

2021-01-19 09:11 UTC, Gelnas commented on src/main/java/com/training/core/model/Tracking.java
> +    @Column(name = "registration_time")
@vibriss, это нужно ещё раз обсудить. Та переменная будет использоваться. А creation_time во всех сущностях будет выполнять одну и ту же функцию. Рамиль, сказал, что можно дублировать и вроде как такая практика есть)

2021-01-19 09:12 UTC, Gelnas commented on src/main/java/com/training/core/model/Address.java
> +    @Column(name = "flat")
Ну это смотря какой английский. Мне не принципиально. Можем и на американском))

2021-01-19 09:17 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Tracking.java
> +    @Column(name = "registration_time")
Давайте уберем registrationTime.

2021-01-19 09:19 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Address.java
> +    @Column(name = "flat")
flat - британский, apartment - американский, насколько принципиально? Я не против поменять.

2021-01-19 10:47 UTC, Gelnas commented on src/main/java/com/training/core/model/Tracking.java
> +    @Column(name = "registration_time")
ok

2021-01-19 20:12 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Cargo.java
> +    private BigDecimal declareitedValue;
declareitedValue -> declaredValue

2021-01-19 20:21 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Returns.java
> +    private Delivery delivery;
delivery не должно удаляться, если удаляется returns

2021-01-19 20:23 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Tracking.java
> +public class Tracking {
Должен быть еще trackingNumber

2021-01-20 12:27 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Delivery.java
> +    private Tracking trackingNumber;
Один ко многим.

2021-01-20 12:30 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Delivery.java
> +    private Client client;
Один client заказывает много deliveri. Много к одному.

2021-01-20 12:32 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Delivery.java
> +public class Delivery {
Мне кажется у delivery не хватает trackingNumber?

2021-01-20 12:43 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Delivery.java
> +    private Enum status;
Мне кажется тут что то не так. Надо создать класс enam-а со значениями, у тут указать этот класс и как это значение будет хранится в базе. Предлагаю @Enumerated(EnumType.STRING).

2021-01-20 12:51 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Label.java
> +    private byte[] label;
Если у чека chequeFile, то логично чтобы здесь было labelFile. Надо привести к какому-то единообразному виду.

2021-01-20 12:53 UTC, Gelnas commented
Хорошо. Переименовать просила Мария, если Вы помните. Мне тоже с файл больше нравится
--
Отправлено из Mail.ru для Android среда, 20 января 2021г., 16:52 +04:00 от Valeriy Emelyanov  notifications@github.com :

>@ValeriyEmelyanov commented on this pull request.
>----------------------------------------------------------------------
>In  src/main/java/com/training/core/model/Label.java :
> +    @Id
>+    @GeneratedValue(strategy = GenerationType.IDENTITY)
>+    private Long id;
>+
>+    /**
>+     * Information on delivery
>+     */
>+    @OneToOne(cascade = CascadeType.PERSIST)
>+    @JoinColumn(name = "delivery_id", referencedColumnName = "id")
>+    private Delivery delivery;
>+
>+    /**
>+     * File with label
>+     */
>+    @Column(name = "label")
>+    private byte[] label;
>
>Если у чека chequeFile, то логично чтобы здесь было labelFile. Надо привести к какому-то единообразному виду.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2021-01-20 13:35 UTC, Gelnas commented on src/main/java/com/training/core/model/Tracking.java
> +public class Tracking {
@ValeriyEmelyanov , мне id переименовать? Ведь насколько я помню, id = trackingNumber?

2021-01-20 17:47 UTC, ramilmm commented on src/main/java/com/training/core/model/DeliveryStatus.java
> +
лишние строки

2021-01-20 17:54 UTC, ramilmm requested changes

2021-01-20 17:54 UTC, ramilmm commented on src/main/java/com/training/core/model/Feedback.java
> +
лишняя строка

2021-01-20 17:54 UTC, ramilmm commented on src/main/java/com/training/core/model/Label.java
> +
лишняя строка

2021-01-20 17:54 UTC, ramilmm commented on src/main/java/com/training/core/model/Returns.java
> +
лишняя строка

2021-01-20 17:54 UTC, ramilmm commented on src/main/java/com/training/core/model/Returns.java
> +    private String reason;
Лучше сделать ENUM для этого поля и определить конкретные возможные причины

2021-01-20 17:54 UTC, ramilmm commented on src/main/java/com/training/core/model/Tracking.java
> +
лишняя строка

2021-01-20 17:54 UTC, ramilmm commented on src/main/java/com/training/core/model/Tracking.java
> +    private Integer trackingNumber;
Трек-номер обычно предполагает наличие символов и цифр. Лучше сделать String

2021-01-21 09:05 UTC, ramilmm approved these changes

2021-01-21 18:15 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Label.java
> +    @Column(name = "labelFile")
`@Column(name = "label_file")`

2021-01-21 18:22 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Tracking.java
> +    private Delivery delivery;
У нас получается двойное указание на delivery: delivery_id и trackingNumber. Мне кажется достаточно указания trackingNumber. Записи в трекинг будут делаться и из других сервисов. Другие сервисы могут не знать delivery_id. А trakcingNumber обязаны знать. Предлагаю совсем убрать это поле.

2021-01-21 18:23 UTC, Gelnas commented on src/main/java/com/training/core/model/Tracking.java
> +    private Delivery delivery;
Я так поняла это необходимость

2021-01-21 18:41 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Delivery.java
> +public class Delivery {
Добавить trackingNumber

2021-01-21 18:50 UTC, ramilmm requested changes

2021-01-21 18:50 UTC, ramilmm commented on src/main/java/com/training/core/model/Address.java
> +    @Column(name = "apartment ")
лишний пробел в названии

2021-01-21 18:50 UTC, ramilmm commented on src/main/java/com/training/core/model/Cargo.java
> +    @Column(name = "declaredValue")
declared_value

2021-01-21 18:50 UTC, ramilmm commented on src/main/java/com/training/core/model/Returns.java
> +    @JoinColumn(name = "delivery-id", referencedColumnName = "id")
delivery_id

2021-01-21 18:50 UTC, ramilmm commented on src/main/java/com/training/core/model/Returns.java
> +    private ReturnReason reason;
@Enumerated(String)

2021-01-21 18:50 UTC, ramilmm commented on src/main/java/com/training/core/model/Tracking.java
> +    @Column(name = "trackingNumber")
tracking_number

2021-01-21 19:06 UTC, ramilmm approved these changes

2021-01-21 19:11 UTC, ValeriyEmelyanov approved these changes

2021-01-21 19:12 UTC, merged