Generates tracking number
Transport-company/core pull request #12
Opened 2021-01-31 18:23 UTC by Prokopyevt

2021-01-31 20:14 UTC, ramilmm requested changes

2021-01-31 20:14 UTC, ramilmm commented on src/main/java/com/training/core/service/TrackingNumberGeneratingService.java
> +     /**
javadocs пишутся над методом

2021-01-31 20:14 UTC, ramilmm commented on src/main/java/com/training/core/service/impl/TrackingNumberGeneratingServiceImpl.java
> +    public String generateStringTrackingNumber() {
@Override

2021-01-31 20:14 UTC, ramilmm commented on src/main/java/com/training/core/service/impl/TrackingNumberGeneratingServiceImpl.java
> +        String trackingNumber = UUID.randomUUID().toString();
сгенеренный UUID проходит по ограничению на длину поля trackNumber в базе?

2021-01-31 20:14 UTC, ramilmm commented on src/main/java/com/training/core/service/impl/TrackingNumberGeneratingServiceImpl.java
> +        if (existsInTheDatabase == true) {
если хочешь проверить на true, то достаточно написать if(existsInTheDatabase), или if(!existsInTheDatabase) если хочешь проверить на false.

2021-01-31 20:14 UTC, ramilmm commented on src/main/java/com/training/core/service/impl/TrackingNumberGeneratingServiceImpl.java
> +        boolean existsInTheDatabase = randomTrackingNumber.equals(trackingNumber);
как это работает?

2021-01-31 20:14 UTC, ramilmm commented on src/main/java/com/training/core/service/impl/TrackingNumberGeneratingServiceImpl.java
> +            return newTrackingNumber;
Если ты сгенерил трек номер, он есть в базе, ты генеришь новый и сразу возвращаешь его без проверки? а что если и второй сгенеренный трек номер есть в базе?

2021-02-01 06:15 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/service/TrackingNumberGeneratingService.java
> +      * method generates a track number
Method с большой буквы,
track -> tracking
в конце предложения не помешает точка

2021-02-01 06:30 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/service/impl/TrackingNumberGeneratingServiceImpl.java
> +        boolean existsInTheDatabase = randomTrackingNumber.equals(trackingNumber);
чтобы понять, существует в базе такой trackingNumber или нет надо обращаться к DeliveryService: 
`if (deliveryService.existsTrackNumber(trackingNumber)) ...`

2021-02-06 14:41 UTC, closed without merging