Core 18/delivery integration tests
Transport-company/core pull request #20
Opened 2021-02-08 13:54 UTC by ValeriyEmelyanov

Delivery controller integration tests

2021-02-10 12:38 UTC, ramilmm requested changes
Я зашёл в PR с названием "delivery integration tests" и не увидел ни одного теста. Вопрос: зачем создан PR? PR создаётся на мёрж изменений в мастер, то есть тут должна быть ветка с готовой реализацией. Не нужно создавать ПР сразу после первого коммита в свою ветку разработки фичи. Я, как ваш коллега-разработчик, не должен по 100 раз заходить ваш вечно открытый ПР и каждый раз тратить своё время чтобы посмотреть добавил ли ты какой-то код сюда или ещё нет. Нельзя так делать

2021-02-10 12:38 UTC, ramilmm commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
Что это и зачем?

2021-02-11 05:28 UTC, ValeriyEmelyanov commented
> не увидел ни одного теста

Создал ветку, все запушил в нее, (если зайдешь в ветку, то там все есть), затем сделал пул реквест. Делал вроде все как обычно. Может быть подскажешь, почему почему пул реквест не все содержит, что есть в ветке и как исправить?

2021-02-11 05:32 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
С помощью ObjectMapper из dto (..Request) генерю Json. Иначе ObjectMapper  выпадает в исключение, просит конструктор без аргументов, т.е. ему нужно указание как создавать Json объект.

2021-02-11 05:38 UTC, ValeriyEmelyanov commented
Если нажать на "Load diff", то все появляется. См. class DeliveryControllerImplTest

2021-02-11 05:39 UTC, ramilmm requested changes
Не стал писать одни и те же комменты везде, но все комменты можно отнести к каждому тесту.

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
>      void create1() throws Exception {
плохое название метода

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +        DeliveryRequest request = getDelivery1(true);
плохое название метода

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    private DeliveryRequest getDelivery1(boolean enabledNotifications) {
плохое название метода

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    void delete1() throws Exception {
плохое название метода

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +        assertEquals(deliveryCount, deliveryRepository.findAll().size());
assertAll( () -> assertequals....,
() -> assertEquals()...)

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    void create1Again() throws Exception {
плохое название метода

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +        assertEquals(deliveryCount, deliveryRepository.findAll().size());
assertAll(() -> assert,
() -> assert,
() -> assert....)

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    void create2() throws Exception {
плохое название метода

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +        DeliveryRequest request = getDelivery2();
плохое название метода

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +        assertEquals(deliveryCount, cargoRepository.findAll().size());
assertAll()

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    private DeliveryRequest getDelivery2() {
Такие объекты нужно создавать с помощью паттерна MotherObject.

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    private CargoRequest getCargo2() {
Такие объекты нужно создавать с помощью паттерна MotherObject.

2021-02-11 05:39 UTC, ramilmm commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    void getFilteredList() throws Exception {
что проверяет тест? По названию метода можно сказать, что он возвращает отфильтрованный список. Название должно содержать что проверяется, при каких условиях и что ожидается. Например, givenNotNullRequest_whenCreateFeature_thenResponseStatusOk

2021-02-11 05:42 UTC, ramilmm commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
Эта аннотация не нужна чтобы генерить json из объекта

2021-02-11 05:45 UTC, ramilmm commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
objectMapper.configure(WRAP_ROOT_VALUE, false)
ObjectWriter writer = objectMapper.getWriter().withDefaultPrettyPrinter();
writer.writeValueAsString(request)

2021-02-11 07:45 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
Ошибся с описанием и направлением. Не из dto (..Request) (тут проблем нет), а из Json в dto (..Response). ObjectMapper выпадает в исключение, просит конструктор без аргументов для dto (..Response) (а поля final), т.е. ему нужно указание как создавать dto объект.

2021-02-11 09:03 UTC, ramilmm commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
Можешь скинуть кусок кода, в котором падает ошибка? readValue(body, ...Response.class) должно норм работать

2021-02-11 09:33 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.training.core.dto.response.DeliveryResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at  [Source: (String)"{"id":1,"enabledNotifications":true,"sum":0.00,"trackingNumber":null,"isPaid":false,"status":"REGISTERED","cargo":{"id":1,"weight":0.4,"declaredValue":1000.00,"length":15.0,"width":10.0,"height":5.0,"created":"2021-02-11T12:30:23.9560917","updated":"2021-02-11T12:30:23.9560917"},"sender":{"id":1,"lastName":"Ivanov","firstName":"Ivan","middleName":"Ivanovich","birthday":"1970-11-20","phoneNumber":"80123456789","email":"Ivanov_II@gmail.com","created":"2021-02-11T12:30:23.8520857","updated":"2021-0"[truncated 783 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1615)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1332)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436)
	at com.training.core.controller.impl.DeliveryControllerImplTest.create1(DeliveryControllerImplTest.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambd [...]

2021-02-11 09:34 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
на строке
`        DeliveryResponse response = objectMapper.readValue(content, DeliveryResponse.class);`

2021-02-11 11:34 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
>      void create1() throws Exception {
Изменил

2021-02-11 11:34 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    private DeliveryRequest getDelivery1(boolean enabledNotifications) {
Изменил

2021-02-11 11:34 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +        assertEquals(deliveryCount, deliveryRepository.findAll().size());
Сделал

2021-02-11 11:35 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +        assertEquals(deliveryCount, cargoRepository.findAll().size());
Сделал

2021-02-11 11:35 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    private CargoRequest getCargo2() {
Сделал

2021-02-11 11:35 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    void getFilteredList() throws Exception {
Изменил

2021-02-11 11:44 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    private DeliveryRequest getDelivery2() {
Сделал

2021-02-11 11:45 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +        assertEquals(deliveryCount, deliveryRepository.findAll().size());
Сделал

2021-02-11 11:45 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/controller/impl/DeliveryControllerImplTest.java
> +    void create2() throws Exception {
Изменил

2021-02-11 11:49 UTC, ramilmm commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
ошибка решается первой ссылкой в гугле.
В корне проекта создай lombok.config и пропиши lombok.anyConstructor.addConstructorProperties=true

2021-02-11 13:24 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
Не работает
![image](https://user-images.githubusercontent.com/50806902/107642174-91f2f100-6c85-11eb-976a-5becd3ac094c.png)

2021-02-12 18:13 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/response/ClientResponse.java
> +@JsonDeserialize(builder = ClientResponse.ClientResponseBuilder.class)
помогло: lombok.config
```
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
lombok.anyConstructor.addConstructorProperties = true
```

2021-02-13 17:15 UTC, Gelnas approved these changes

2021-02-13 20:46 UTC, ValeriyEmelyanov commented on src/test/resources/application.yml
> +    url: jdbc:h2:mem:core;DB_CLOSE_DELAY=-1
Просто core, меньше букв (h2 in memory точно не продаушн)

2021-02-16 16:33 UTC, vibriss approved these changes

2021-02-17 10:51 UTC, merged