Core 22/calc delivery sum
Transport-company/core pull request #23
Opened 2021-02-25 17:03 UTC by ValeriyEmelyanov

Для реализации расчета суммы доставки добавил сущность Tariff и для нее реализовал контроллер, сервис и репозиторий. Сумму сначала рассчитываю в зависимости от расстояния доставки (пока случайное число), затем, если необходимо увеличиваю в зависимости от веса/объема. Модульные тесты написал только для DeliverySumCalculatingService. Для тарифов на тесты будет отдельная задача.

2021-02-25 19:23 UTC, mariavv commented on src/main/java/com/training/core/service/impl/DeliveryDistanceCalculatingServiceImpl.java
> +        return (int) (Math.random() * ++max) + min;
Это как то странно. Наверное лучше так: return (int) (Math.random() * (max - min))+ min;

2021-02-26 08:03 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/service/impl/DeliveryDistanceCalculatingServiceImpl.java
> +        return (int) (Math.random() * ++max) + min;
Исправил

2021-02-26 08:17 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/request/TariffRequest.java
> +    private final float weightUnit;
Исправил

2021-02-26 08:17 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/request/TariffRequest.java
> +    private final int minDistance;
Исправил

2021-02-26 11:18 UTC, ramilmm requested changes

2021-02-26 11:18 UTC, ramilmm commented on src/test/java/com/training/core/service/impl/OrderServiceImplTest.java
> +    DeliveryService deliveryService;
Спринг в тестировании нужен только для контроллеров, потому что там нужно поднимать контекст и всякое такое. В сервисах, утилитах и ещё где-то нужны чистые junit тесты. Тестируем только конкретные классы. 
Например, если тестируем OrderService, мокаем всё что используется в нём и работаем только с этим классом

2021-02-26 11:18 UTC, ramilmm commented on src/test/java/com/training/core/util/TestCargo.java
> +        return Cargo.builder()
лучше использовать MotherObject паттерн

2021-02-26 13:16 UTC, mariavv approved these changes

2021-02-26 15:15 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/service/impl/OrderServiceImplTest.java
> +    DeliveryService deliveryService;
Так это и есть просто модульный тест для сервиса OrderServiceImpl.
```
@InjectMocks
**OrderServiceImpl** orderService;
```
Здесь нет спрингового контекста. Мокаем необходимые компоненты, для этих компонентов не надо указывать конкретную реализацию.

2021-02-26 15:20 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/util/TestCargo.java
> +        return Cargo.builder()
Это и есть MotherObject. Из того, что нашел по данному вопросу https://blog.codeleak.pl/2014/06/test-data-builders-and-object-mother.html

2021-02-26 15:22 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/service/impl/TariffServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Not found the tariff with id " + id));
т.е. для каждой сущности создать свое NotFoundSomeEnityException?

2021-02-26 15:33 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/service/impl/DeliverySumCalculatingServiceImpl.java
> +        Assert.notNull(date, ErrorMessages.NULL_DATE.getErrorMessage());
Исправил

2021-02-26 15:34 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/repository/TariffRepository.java
> +
Исправил

2021-02-26 15:37 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/request/TariffRequest.java
> +    @Min(value = 0)
Исправил

2021-02-26 16:05 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/config/ConversionConfig.java
> +        registry.addConverter(new TariffRequestToTariffConverter());
Исправил, конфиг убрал

2021-02-26 16:58 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/service/impl/TariffServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Not found the tariff with id " + id));
создал специфичные эксепшены для каждой сущности

2021-03-01 05:37 UTC, ramilmm commented on src/test/java/com/training/core/service/impl/OrderServiceImplTest.java
> +    DeliveryService deliveryService;
что такое BaseTest?

2021-03-01 05:45 UTC, ramilmm commented on src/test/java/com/training/core/util/TestCargo.java
> +        return Cargo.builder()
а, ок. Прост с первого взгляда не скажешь что это реализация MotherObject

Пример из рабочего проекта:

MotherObject.java
----
public SendMessageRequestBuilder getSendMessageRequest() {
  return new SendMessageRequestBuilder.Default();
}

public static final class SendMessageRequest {
 public String messageId;
 public String clientId;
 ......
}
-----

SendMessageRequestBuilder.java
-----

SendMessageRequest please();

SendMessageRequestBuilder any();

SendMessageRequestBuilder withMessageId(String messageId);

SendMessageRequestBuilder  withClientId(String clientId);

......

final class Default implements SendMessageRequestBuilder {

 private MotherObject.SendMessageRequest request = new Mother......;
 
  SendMessageRequest please() {
   return request;
  }

SendMessageRequestBuilder any() {
 return this.withMessageId("14124")
                  .withClientId("sr1j214k");
}


SendMessageRequestBuilder withMessageId(String messageId) {
   request.setMessageId(messageId);
   
return this;
}

......

}

-----

2021-03-01 05:46 UTC, ramilmm commented on src/test/java/com/training/core/util/TestCargo.java
> +        return Cargo.builder()
это позволяет более гибко настраивать получаемые объекты, не создавая лишних методов

2021-03-01 06:51 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/service/impl/OrderServiceImplTest.java
> +    DeliveryService deliveryService;
initMocks() стал deprecated. Чтобы не дублировать один и тот же код во всех модульных тестах, открытие и завершение мок-сессии вынесено в базовый класс. Сам подход описан здесь: https://www.javadoc.io/doc/org.mockito/mockito-core/3.6.0/org/mockito/MockitoAnnotations.html Но так как они пишут "See also MockitoSession ..." https://www.javadoc.io/static/org.mockito/mockito-core/3.6.0/org/mockito/MockitoSession.html, то сделал все это с MockitoSession.

2021-03-01 06:54 UTC, ValeriyEmelyanov commented on src/test/java/com/training/core/util/TestCargo.java
> +        return Cargo.builder()
Насколько понимаю, это то что в статье описано по заголовком "Object Mother and Test Data Builder combined"

2021-03-01 09:14 UTC, ramilmm commented on src/test/java/com/training/core/util/TestCargo.java
> +        return Cargo.builder()
ага, подход такой

2021-03-01 09:16 UTC, ramilmm approved these changes

2021-03-01 10:49 UTC, merged