Core 02
Transport-company/core pull request #3
Opened 2021-01-20 11:14 UTC by BrynzaA

Добавлены SQL таблицы для моделей

2021-01-20 11:58 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +CREATE SEQUENCE IF NOT EXISTS hibernate_sequence start 1000 increment 1;
Мы обсуждали, что не будем использовать сквозную генерацию для идентификаторов. Какой в этом смысл? К тому же, насколько понимаю, эо узкое место производительности. С моей т.з. каждая таблица должна иметь свой пул идентификаторов.

2021-01-20 12:03 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    id                    serial PRIMARY KEY,
Если `Long id`, то здесь должно быть: `id bigserial PRIMARY KEY,`

2021-01-20 12:06 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    apartment    varchar(255)       NOT NULL,
едва ли везде нужно 255 символов, предлагаю подойти более дифференцировано

2021-01-20 12:09 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    updated      date               NOT NULL
date -> timestamp

2021-01-20 12:21 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    declareited_value   decimal      NOT NULL,
Для "денег" numeric(19,2)? Типа такой тип JPA создает из BigDecimal при автоматическом создании таблиц. Сам не проверял. Ну для остальных денежных типов так же.

2021-01-20 12:30 UTC, ramilmm requested changes

2021-01-20 12:30 UTC, ramilmm commented on src/main/java/com/training/core/model/Delivery.java
> +    private Enum status;
@Enumerated(EnumType.STRING) чтобы в базе хранилось конкретное значение мб?

2021-01-20 12:30 UTC, ramilmm commented on src/main/java/com/training/core/model/Delivery.java
> +    private Address sendingAddress;
Это адрес откуда посылка ушла? Не очень нравится название sendingAddress, но пока не могу придумать другое)

2021-01-20 12:30 UTC, ramilmm commented on src/main/java/com/training/core/model/Feedback.java
> +    private String content;
message? Под контентом обычно подразумевается не только текст, но ещё что-то(картинка). Если отзыв содержит только текст, то лучше message

2021-01-20 12:30 UTC, ramilmm commented on src/main/java/com/training/core/model/Tracking.java
> +    private String city;
Как пользователю будет показываться история отслеживания посылки?
То есть, например посылка прошла 4 города, пользователь должен увидеть где и когда была посылка

2021-01-20 12:30 UTC, ramilmm commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    reason       varchar(255)       NOT NULL,
тут нужно 255 символов для причины?

2021-01-20 12:30 UTC, ramilmm commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    city         varchar(255)       NOT NULL,
Не думаю, что есть город, название которого будет хотя бы в 100 символов

2021-01-20 12:35 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    tracking_id           int8                NOT NULL,
Здесь не может быть tracking_id и соответственно внешнего ключа, потому что связь один ко многим. Когда Гельназ доделаем модель, должно появиться поле trackingNumber.

2021-01-20 12:36 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +CREATE TABLE IF NOT EXISTS tracking
Должно будет появиться поле trackingNumber.

2021-01-20 12:45 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +CREATE TYPE delivery_status AS ENUM ('PICKED_UP', 'ON_DELIVERY', 'DELIVERED', 'FAILED', 'LOST');
Надо дождаться, пока Гельназ закончит модель. Если статус будет хранится как строка (@Enumerated(EnumType.STRING)), то смысла в этой таблице не будет.

2021-01-20 16:08 UTC, vibriss commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    city         varchar(255)       NOT NULL,
Предлагаю:
    region                       varchar(32)    NOT NULL,
    city                          varchar(32)    NOT NULL,
    street                       varchar(32),
    house                       varchar(4),
    apartment                 varchar(4),

2021-01-20 16:18 UTC, vibriss commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    declareited_value   decimal      NOT NULL,
*declared_value

2021-01-20 18:10 UTC, ramilmm commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    city         varchar(255)       NOT NULL,
region (32) -  Республика Северная Осетия - Алания - сразу вызывает ошибку
street (32) - улица "Территория, изъятая из земель подсобного хозяйства Всесоюзного центрального совета профессиональных союзов для организации крестьянского хозяйства" - сразу вызывает ошибку
house (4) - 71к4Г-Дс5 - сразу вызывает ошибку
app (4) - думаю тут тоже стоит увеличить

2021-01-22 16:35 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    shipping_address_id   bigserial          NOT NULL,
bigserial используется для полей с автоинкрементацией (https://metanit.com/sql/postgresql/2.3.php), т.е. генерируемые первичные ключи, int8 было нормально

2021-01-22 16:37 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    delivery_id  bigserial          NOT NULL,
int8

2021-01-22 16:39 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    reason       varchar(13)        NOT NULL,
точно обычно не высчитывается, округляется до числа кратного 10 или 5. Предлагаю 15

2021-01-22 16:39 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    delivery_id     bigserial          NOT NULL,
int8

2021-01-22 16:56 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    city         varchar(28)        NOT NULL,
50

2021-01-22 16:57 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    street       varchar(95)        ,
street 120

2021-01-22 16:58 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__DB.sql
> +    city            varchar(28)        NOT NULL,
city 50

2021-01-23 19:02 UTC, closed without merging