Core 11/interfaces
Transport-company/core pull request #4
Opened 2021-01-22 08:20 UTC by ValeriyEmelyanov

Созданы интерфейсы контроллеров полностью: объявления методов, маппинг, javadocs, swager docs.
Созданы интерфейсы контроллеров, только объявления классов (чтобы понимать общую картину).
Класс dto OrderPageResponse создан полностью, образец для подобных ..PageResponse.
Для остальных классов dto созданы только объявления, без наполнения (необходимы для объявления методов контроллеров).

2021-01-22 11:40 UTC, vibriss commented on src/main/java/com/training/core/control/FeedbackController.java
> +package com.training.core.control;
пакет с контроллерами будем называть "control", не "controllers"?

2021-01-22 13:24 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/control/FeedbackController.java
> +package com.training.core.control;
исправил на controller

2021-01-22 18:56 UTC, ramilmm requested changes
Просмотреть описания эндпоинтов для сваггера. Добавить статусы.

2021-01-22 18:56 UTC, ramilmm commented on src/main/java/com/training/core/controller/FeedbackController.java
> +                            schema = @Schema(implementation = FeedbackPageResponse.class)))
добавить 400 и 500 статусы

2021-01-22 18:56 UTC, ramilmm commented on src/main/java/com/training/core/controller/FeedbackController.java
> +            @ApiResponse(responseCode = "404", description = "not found", content = @Content)
500 статус

2021-01-22 18:56 UTC, ramilmm commented on src/main/java/com/training/core/controller/FeedbackController.java
> +                            mediaType = "application/json",
400 и 500 статус

2021-01-22 18:56 UTC, ramilmm commented on src/main/java/com/training/core/controller/FeedbackController.java
> +    ResponseEntity<FeedbackResponse> update(
400 и 500 статус

2021-01-22 18:56 UTC, ramilmm commented on src/main/java/com/training/core/controller/FeedbackController.java
> +            @ApiResponse(responseCode = "404", description = "not found", content = @Content)
500 статус

2021-01-22 18:56 UTC, ramilmm commented on src/main/java/com/training/core/controller/OrderController.java
> +                            schema = @Schema(implementation = OrderPageResponse.class)))
500 статус добавить во все описания контроллеров

2021-01-22 18:56 UTC, ramilmm commented on src/main/java/com/training/core/controller/OrderController.java
> +    @PostMapping
400 статус

2021-01-22 18:56 UTC, ramilmm commented on src/main/java/com/training/core/controller/OrderController.java
> +    @PutMapping(ID_PATH_VARIABLE)
400 и 500 статус, да и вообще во всех контроллерах просмотри описание эндпоинтов

2021-01-22 20:06 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/FeedbackController.java
> +                            schema = @Schema(implementation = FeedbackPageResponse.class)))
Исправил

2021-01-22 20:07 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/FeedbackController.java
> +            @ApiResponse(responseCode = "404", description = "not found", content = @Content)
исправил

2021-01-22 20:08 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/FeedbackController.java
> +                            mediaType = "application/json",
исправил

2021-01-22 20:09 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/FeedbackController.java
> +            @ApiResponse(responseCode = "404", description = "not found", content = @Content)
исправил

2021-01-22 20:18 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/OrderController.java
> +                            schema = @Schema(implementation = OrderPageResponse.class)))
исправил

2021-01-22 20:27 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/OrderController.java
> +    @PostMapping
исправил

2021-01-22 20:28 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/OrderController.java
> +    @PutMapping(ID_PATH_VARIABLE)
везде добавил

2021-01-23 18:19 UTC, vibriss approved these changes

2021-01-23 18:50 UTC, Gelnas approved these changes

2021-01-23 19:41 UTC, merged