fixing models and add migration
Transport-company/core pull request #6
Opened 2021-01-24 19:33 UTC by Gelnas

Доработана модель и сделана ещё одна миграция

2021-01-24 20:28 UTC, vibriss reviewed
Может быть, для клиента так же как и для курьера, добавить birthday?
    /**
     * Date of birth
     */
    @Column(name = "birthday", nullable = false)
    private LocalDate birthday;

    birthday                 date                NOT NULL,

2021-01-24 20:28 UTC, vibriss commented on src/main/resources/db/migration/V1_0_0_2__alter_table.sql
> -ALTER TABLE client RENAME column surname       to last_name;
У меня вопрос.
Я понимаю, что те sql-скрипты, что уже опубликованы в репозитории, правятся только последующими скриптами. Но на текущий момент, может, допустимо запушить в main отредактированный основной скрипт? Все равно пока БД не используется.

2021-01-24 20:28 UTC, vibriss commented on src/main/resources/db/migration/V1_0_0_2__alter_table.sql
> +ALTER TABLE client add    column    phone_number   varchar (20);
Я назвал колонку "phone" и установил длину поля в 11 символов. На каком варианте остановимся для единообразия? И еще надо добавить NOT NULL UNIQUE.

2021-01-25 05:45 UTC, ramilmm commented on src/main/resources/db/migration/V1_0_0_2__alter_table.sql
> -ALTER TABLE client RENAME column surname       to last_name;
> У меня вопрос.
> Я понимаю, что те sql-скрипты, что уже опубликованы в репозитории, правятся только последующими скриптами. Но на текущий момент, может, допустимо запушить в main отредактированный основной скрипт? Все равно пока БД не используется.

нет, добавление поля или изменение название поля только в новом скрипте. У большинства скрипт уже отработал локально и скрипт зафиксировался в бд, при его изменении проект перестанет запускаться

2021-01-25 06:02 UTC, ramilmm requested changes

2021-01-25 06:02 UTC, ramilmm commented on src/main/resources/db/migration/V1_0_0_2__alter_table.sql
> +ALTER TABLE client add    column    phone_number   varchar (20);
phone_number varchar(11) NOT NULL UNIQUE

2021-01-25 08:19 UTC, ValeriyEmelyanov commented
> Может быть, для клиента так же как и для курьера, добавить birthday?

Да, мы говорили, клиенту надо добавить дату рождение, не забываем про camelCase: LocalDate birthDate (birth_date в таблице)

2021-01-25 08:23 UTC, vibriss commented on src/main/resources/db/migration/V1_0_0_2__alter_table.sql
> -ALTER TABLE client RENAME column surname       to last_name;
Понял, спасибо

2021-01-25 15:16 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Client.java
> +    private String phoneNumber;
name = "phone_number"

2021-01-25 15:19 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Delivery.java
>      private Address sendingAddress;
Думаю, тут тоже надо ManyToOne

2021-01-25 15:19 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/model/Delivery.java
>      private Address shippingAddress;
ManyToOne

2021-01-25 15:40 UTC, ValeriyEmelyanov approved these changes

2021-01-25 20:42 UTC, vibriss approved these changes

2021-01-25 20:46 UTC, merged