Core 15/deliveries
Transport-company/core pull request #8
Opened 2021-01-29 15:32 UTC by ValeriyEmelyanov

Реализация DeliveryController.

2021-01-29 17:07 UTC, Gelnas commented on src/main/java/com/training/core/config/ConversionConfig.java
> +
Я вынесла toAddressConverter и пр. в поля класса, обозначив их аннотацией @Component. Насколько это решение верное?

2021-01-29 18:42 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/config/ConversionConfig.java
> +
С точки зрения слабой связанности зависимостей может быть и верно. Но с др. стороны это не интерфейсы и не вписывается, что с мапперами работаем только через спринговский ConversionService.

2021-01-30 17:00 UTC, mariavv commented
у меня замечаний нет. Просмотр скорее ознакомительный

2021-01-30 17:25 UTC, vibriss commented on src/main/java/com/training/core/controller/DeliveryController.java
> +    @GetMapping(Urls.Deliveries.Filter.PART)
Urls.Deliveries.FULL + Urls.Deliveries.Filter.PART = "/deliveries" + "filter", кажется, не хватает "/"

2021-01-30 17:30 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/DeliveryController.java
> +    @GetMapping(Urls.Deliveries.Filter.PART)
Да, первый раз когда ошибся, удивился, что работает. Сейчас так оставляю, потому что так красивие. Похоже, что спринг к корневому урлу контроллера сам добавляет слэш.  В гугле сходу объяснения не нашел.

2021-01-30 17:52 UTC, vibriss commented on src/main/java/com/training/core/service/DeliveryService.java
> +     * Method for saving a {@link NotFoundException} in a repository.
Тут подправить надо

2021-01-30 18:08 UTC, vibriss approved these changes

2021-01-30 19:54 UTC, Gelnas commented on src/main/java/com/training/core/service/impl/DeliveryServiceImpl.java
> +        Assert.notNull(id, "Id can not be null");
ErrorMessages

2021-01-30 20:08 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/service/impl/DeliveryServiceImpl.java
> +        Assert.notNull(id, "Id can not be null");
исправил

2021-01-31 16:09 UTC, Gelnas approved these changes

2021-01-31 17:28 UTC, ramilmm requested changes

2021-01-31 17:28 UTC, ramilmm commented on src/main/java/com/training/core/controller/DeliveryController.java
> +    @PatchMapping(ID_PATH_VARIABLE + "/" + Urls.Deliveries.Status.PART)
не нужно это тут делать, в параметрах должна быть константа какая-то

2021-01-31 17:28 UTC, ramilmm commented on src/main/java/com/training/core/service/DeliveryService.java
> + * Service for working with {@link Delivery deliviry} entity.
delivery

2021-01-31 19:24 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/Urls.java
> +            String PART = "status";
http://localhost:8080/api/v1/core/deliveries/{id}/status
? String PART = "{id}/status" ?

2021-01-31 19:32 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/config/ConversionConfig.java
> +                new PageToDeliveryPageResponse(
исходный тип Page<List<Delivery>>, в имени конвертора преобразовал в DeliveryPage

2021-01-31 19:35 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/controller/DeliveryController.java
> +    @PatchMapping(ID_PATH_VARIABLE + "/" + Urls.Deliveries.Status.PART)
исправил

2021-01-31 19:36 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/service/DeliveryService.java
> + * Service for working with {@link Delivery deliviry} entity.
исправил

2021-01-31 19:40 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/config/ConversionConfig.java
> +        converters.add(toAddressConverter);
он дальше используется в конструкторах
        converters.add(
                new DeliveryRequestToDeliveryConverter(
                        toAddressConverter,
                        toCargoConverter,
                        toClientConverter));
и
        converters.add(
                new OrderRequestToDeliveryConverter(
                        toAddressConverter,
                        toCargoConverter,
                        toClientConverter));

2021-01-31 19:57 UTC, ramilmm commented on src/main/java/com/training/core/Urls.java
> +            String PART = "status";
Если ты сделаешь Urls.Deliveries.Status.Part, то будет только 'status' Не очень вижу применение такой штуки.

2021-01-31 19:58 UTC, ramilmm commented on src/main/java/com/training/core/config/ConversionConfig.java
> +        converters.add(toAddressConverter);
а, ок

2021-01-31 19:59 UTC, ramilmm commented on src/main/java/com/training/core/config/ConversionConfig.java
> +                new PageToDeliveryPageResponse(
класс конфиг для конвертера можно немного упростить:

что-то вроде:
@Configuration
public class ConverterConfig implements WebMvcConfigurer {

@Override
public void addFormatters(FormatterRegistry registry) {
  registry.add(new SomeConverter());
  registry.add(new SomeAnotherConverter());
}

}

2021-01-31 21:08 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/Urls.java
> +            String PART = "status";
```
@RequestMapping(Urls.Deliveries.FULL)
public interface DeliveryController {
...
String ID_PATH_VARIABLE_STATUS = ID_PATH_VARIABLE + "/" + Urls.Deliveries.Status.PART;
...
@PatchMapping(ID_PATH_VARIABLE_STATUS)
ResponseEntity<String> changeStatus( ..
```

2021-01-31 21:10 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/config/ConversionConfig.java
> +                new PageToDeliveryPageResponse(
ок

2021-02-01 05:57 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/config/ConversionConfig.java
> +                new PageToDeliveryPageResponse(
Изменил

2021-02-01 13:36 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/Urls.java
> +            String PART = "status";
Может быть для `Urls.Deliveries.Status.PART` сделать: `String PART = "{id}/status";` тогда в интерфейс `Urls.Deliveries.Status` имеет смысл добавить `String FULL = ROOT + "/" + PART;` и `Urls.Deliveries.Status.FULL` можно будет использовать в интеграционных тестах, сам `Urls.Deliveries.Status.PART` указывать в `@RequestMapping` для `changeStatus()`.

2021-02-01 17:20 UTC, Gelnas commented on src/main/java/com/training/core/dto/request/OrderRequest.java
> +    private final boolean enabledNotifications;
Эти данные передаются при заказе? Это разве не в настройках приложения как-то отслеживаться должно? Или клиент для каждого заказа подтверждает, что хочет получать уведомления, конкретно об этом заказе?

2021-02-01 17:21 UTC, ValeriyEmelyanov commented on src/main/java/com/training/core/dto/request/OrderRequest.java
> +    private final boolean enabledNotifications;
Да, клиент по конкретному заказу заявляет, хочет ли он получать уведомления.

2021-02-02 05:56 UTC, merged